//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.LocalResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinalProject.LocalResource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua conta no {0}.
        /// </summary>
        public static string AccountResponseEmailSubject {
            get {
                return ResourceManager.GetString("AccountResponseEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferências padrões.
        /// </summary>
        public static string AdminPreferencesViewHeader {
            get {
                return ResourceManager.GetString("AdminPreferencesViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferências para serem utilizadas caso um estudante ainda não tenha definido as suas preferências.
        /// </summary>
        public static string AdminPreferencesViewSubheader {
            get {
                return ResourceManager.GetString("AdminPreferencesViewSubheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerencie seus horários livres.
        /// </summary>
        public static string AgendaViewHeader {
            get {
                return ResourceManager.GetString("AgendaViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a outros estudantes os dias e  horários que você está disponível para videoconferência.
        /// </summary>
        public static string AgendaViewSubHeader {
            get {
                return ResourceManager.GetString("AgendaViewSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string AgendaViewTitle {
            get {
                return ResourceManager.GetString("AgendaViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string AndOperator {
            get {
                return ResourceManager.GetString("AndOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responda a essa pergunta.
        /// </summary>
        public static string AnswerQuestionFieldPlaceholder {
            get {
                return ResourceManager.GetString("AnswerQuestionFieldPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovadas.
        /// </summary>
        public static string ApprovedTagsNodeText {
            get {
                return ResourceManager.GetString("ApprovedTagsNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para aprovar uma tag, arraste-a para &quot;Aprovadas&quot;.
        /// </summary>
        public static string ApproveTagInstructionText {
            get {
                return ResourceManager.GetString("ApproveTagInstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponível.
        /// </summary>
        public static string AvailableEventTitle {
            get {
                return ResourceManager.GetString("AvailableEventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agendado.
        /// </summary>
        public static string BusyEventTitle {
            get {
                return ResourceManager.GetString("BusyEventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha suas tags.
        /// </summary>
        public static string ChooseTagsText {
            get {
                return ResourceManager.GetString("ChooseTagsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recolher tudo.
        /// </summary>
        public static string CollpaseAllNodesTreeTitle {
            get {
                return ResourceManager.GetString("CollpaseAllNodesTreeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para começar a usar sua conta, você só precisa validar seu e-mail clicando &lt;a href=&quot;{0}&quot;&gt;aqui&lt;/a&gt;..
        /// </summary>
        public static string ConfirmAccountEmailMessage {
            get {
                return ResourceManager.GetString("ConfirmAccountEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certeza de que deseja deletar essa tag?.
        /// </summary>
        public static string ConfirmTagDeletionModalMessage {
            get {
                return ResourceManager.GetString("ConfirmTagDeletionModalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        public static string ConfirmTagDeletionModalTitle {
            get {
                return ResourceManager.GetString("ConfirmTagDeletionModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome da formação é obrigatório.
        /// </summary>
        public static string CreateGradeViewModelNameFieldRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CreateGradeViewModelNameFieldRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Seu pedido para cadastrar a universidade &lt;b&gt;{0}&lt;/b&gt; foi negado pelo seguinte motivo:&lt;/p&gt;&lt;blockquote&gt;&lt;q&gt;&lt;i&gt;{1}&lt;i/&gt;&lt;/q&gt;&lt;/blockquote&gt;.
        /// </summary>
        public static string DenyInstitutionRequestEmailMessage {
            get {
                return ResourceManager.GetString("DenyInstitutionRequestEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar perfil.
        /// </summary>
        public static string EditViewTitle {
            get {
                return ResourceManager.GetString("EditViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail enviado para &lt;b&gt;{0}&lt;/b&gt;.
        /// </summary>
        public static string EmailSentTo {
            get {
                return ResourceManager.GetString("EmailSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicione um novo assunto.
        /// </summary>
        public static string EnterTagNamePlaceholderText {
            get {
                return ResourceManager.GetString("EnterTagNamePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao criar tag.
        /// </summary>
        public static string ErrorCreatingTagMessage {
            get {
                return ResourceManager.GetString("ErrorCreatingTagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao deletar tag.
        /// </summary>
        public static string ErrorDeletingTagMessage {
            get {
                return ResourceManager.GetString("ErrorDeletingTagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tag de destino não foi encontrada.
        /// </summary>
        public static string ErrorNotFoundTargetTagMessage {
            get {
                return ResourceManager.GetString("ErrorNotFoundTargetTagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tag de origem deve estar pendente de aprovação.
        /// </summary>
        public static string ErrorNotPendingSourceTagMessage {
            get {
                return ResourceManager.GetString("ErrorNotPendingSourceTagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag não encontrada.
        /// </summary>
        public static string ErrorTagNotFound {
            get {
                return ResourceManager.GetString("ErrorTagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao atualizar tag.
        /// </summary>
        public static string ErrorUpdatingTagMessage {
            get {
                return ResourceManager.GetString("ErrorUpdatingTagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expandir tudo.
        /// </summary>
        public static string ExpandAllNodesTreeTitle {
            get {
                return ResourceManager.GetString("ExpandAllNodesTreeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar apenas as perguntas da minha instituição.
        /// </summary>
        public static string FilterTimelineStudentInstitutionItemsFieldLabel {
            get {
                return ResourceManager.GetString("FilterTimelineStudentInstitutionItemsFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar apenas as minhas perguntas.
        /// </summary>
        public static string FilterTimelineStudentItemsFieldLabel {
            get {
                return ResourceManager.GetString("FilterTimelineStudentItemsFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string FilterTimelineTagsFieldPlaceholder {
            get {
                return ResourceManager.GetString("FilterTimelineTagsFieldPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string FilterTimelineTitleFieldPlaceholder {
            get {
                return ResourceManager.GetString("FilterTimelineTitleFieldPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entendi.
        /// </summary>
        public static string GotItText {
            get {
                return ResourceManager.GetString("GotItText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formação.
        /// </summary>
        public static string GradeNameFieldPlaceholder {
            get {
                return ResourceManager.GetString("GradeNameFieldPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        public static string GradeYearFieldPlaceholder {
            get {
                return ResourceManager.GetString("GradeYearFieldPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrutor.
        /// </summary>
        public static string Instructor {
            get {
                return ResourceManager.GetString("Instructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tag &apos;{0}&apos; não existe em nosso sistema ainda.  Vamos analisá-la e, se aprovarmos, ela aparecerá para você..
        /// </summary>
        public static string InstructorTagNotAdded {
            get {
                return ResourceManager.GetString("InstructorTagNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As tags {0} não existem em nosso sistema ainda. Vamos analisá-las e, se aprovarmos, elas aparecerão para você..
        /// </summary>
        public static string InstructorTagsNotAdded {
            get {
                return ResourceManager.GetString("InstructorTagsNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disciplinas que você pode ajudar outros estudantes.
        /// </summary>
        public static string InstructorTagsViewHeader {
            get {
                return ResourceManager.GetString("InstructorTagsViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicione disciplinas através de tags clicando no botão abaixo.
        /// </summary>
        public static string InstructorTagsViewSubheader {
            get {
                return ResourceManager.GetString("InstructorTagsViewSubheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controle as tags de sua instituição.
        /// </summary>
        public static string ManageTagsViewHeader {
            get {
                return ResourceManager.GetString("ManageTagsViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crie, edite, remova, aprove e rejeite tags da sua instituição.
        /// </summary>
        public static string ManageTagsViewSubHeader {
            get {
                return ResourceManager.GetString("ManageTagsViewSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlar tags.
        /// </summary>
        public static string ManageTagsViewTitle {
            get {
                return ResourceManager.GetString("ManageTagsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} respostas.
        /// </summary>
        public static string MultipleAnswersText {
            get {
                return ResourceManager.GetString("MultipleAnswersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua pergunta &lt;q&gt;&lt;i&gt;{0}&lt;i/&gt;&lt;/q&gt; tem uma nova resposta:
        ///&lt;/p&gt;&lt;blockquote&gt;&lt;q&gt;&lt;i&gt;{1}&lt;i/&gt;&lt;/q&gt;&lt;/blockquote&gt;&lt;/p&gt;.
        /// </summary>
        public static string NewAnswerToQuestionEmailContent {
            get {
                return ResourceManager.GetString("NewAnswerToQuestionEmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova resposta para a sua pergunta no CoLearn.
        /// </summary>
        public static string NewAnswerToQuestionEmailSubject {
            get {
                return ResourceManager.GetString("NewAnswerToQuestionEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sua pergunta tem uma nova resposta.
        /// </summary>
        public static string NewAnswerToQuestionNotificationTitle {
            get {
                return ResourceManager.GetString("NewAnswerToQuestionNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perguntar!.
        /// </summary>
        public static string NewQuestionSubmitButtonText {
            get {
                return ResourceManager.GetString("NewQuestionSubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qual a sua dúvida?.
        /// </summary>
        public static string NewQuestionViewHeader {
            get {
                return ResourceManager.GetString("NewQuestionViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Após descrever sua dúvida, adicione tags para que outros estudantes encontrem sua pergunta mais facilmente..
        /// </summary>
        public static string NewQuestionViewSubheader {
            get {
                return ResourceManager.GetString("NewQuestionViewSubheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova pergunta.
        /// </summary>
        public static string NewQuestionViewTitle {
            get {
                return ResourceManager.GetString("NewQuestionViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma resposta ainda.
        /// </summary>
        public static string NoAnswersText {
            get {
                return ResourceManager.GetString("NoAnswersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para ter acesso ao conteúdo do site, uma instituição deve ser selecionada. Assim, apenas o conteúdo da instituição selecionada será exibido para você..
        /// </summary>
        public static string NoInstitutionModalMessage {
            get {
                return ResourceManager.GetString("NoInstitutionModalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quase pronto.
        /// </summary>
        public static string NoInstitutionModalTitle {
            get {
                return ResourceManager.GetString("NoInstitutionModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este estudante não informou nenhum assunto ainda.
        /// </summary>
        public static string NoInstructorTagsText {
            get {
                return ResourceManager.GetString("NoInstructorTagsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma pergunta encontrada relacionada a você.
        /// </summary>
        public static string NoQuestionFoundText {
            get {
                return ResourceManager.GetString("NoQuestionFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não informou nenhum assunto ainda.
        /// </summary>
        public static string NoSelfInstructorTagsText {
            get {
                return ResourceManager.GetString("NoSelfInstructorTagsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso.
        /// </summary>
        public static string NoticeText {
            get {
                return ResourceManager.GetString("NoticeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail não confirmado. Verifique sua caixa de entrada ou sua caixa de spam.
        /// </summary>
        public static string NotVerifiedEmailErrorMessage {
            get {
                return ResourceManager.GetString("NotVerifiedEmailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OU.
        /// </summary>
        public static string OrOperator {
            get {
                return ResourceManager.GetString("OrOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendentes.
        /// </summary>
        public static string PendingTagsNodeText {
            get {
                return ResourceManager.GetString("PendingTagsNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similaridade mínima entre o seu perfil e os perfis dos instrutores recomendados para você.
        /// </summary>
        public static string PreferencesSimilariryPanelTitle {
            get {
                return ResourceManager.GetString("PreferencesSimilariryPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suas preferências.
        /// </summary>
        public static string PreferencesViewHeader {
            get {
                return ResourceManager.GetString("PreferencesViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Como você deseja que o sistema recomende instrutores para te ajudar?.
        /// </summary>
        public static string PreferencesViewSubheader {
            get {
                return ResourceManager.GetString("PreferencesViewSubheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferências.
        /// </summary>
        public static string PreferencesViewTitle {
            get {
                return ResourceManager.GetString("PreferencesViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoLearn.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Como nenhuma das tags para sua pergunta existe em nosso sistema, sua pergunta não será listada até que pelo menos uma das tags seja aprovada. Enquanto isso, vamos tentar te ajudar com uma lista de materiais tiradas da web!.
        /// </summary>
        public static string QuestionNoTagAded {
            get {
                return ResourceManager.GetString("QuestionNoTagAded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tag &apos;{0}&apos; não existe em nosso sistema ainda.  Vamos analisá-la e, se aprovarmos, ela aparecerá na sua pergunta..
        /// </summary>
        public static string QuestionTagNotAdded {
            get {
                return ResourceManager.GetString("QuestionTagNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sua pergunta deve ter ao menos uma tag.
        /// </summary>
        public static string QuestionTagRequiredErrorMessage {
            get {
                return ResourceManager.GetString("QuestionTagRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As tags {0} não existem em nosso sistema ainda. Vamos analisá-las e, se aprovarmos, elas aparecerão na sua pergunta.
        /// </summary>
        public static string QuestionTagsNotAdded {
            get {
                return ResourceManager.GetString("QuestionTagsNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sua pergunta deve ter um título.
        /// </summary>
        public static string QuestionTitleRequiredErrorMessage {
            get {
                return ResourceManager.GetString("QuestionTitleRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pode ajudar em.
        /// </summary>
        public static string RecommendedStudentBlockCanHelpLabel {
            get {
                return ResourceManager.GetString("RecommendedStudentBlockCanHelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaliação média da comunidade.
        /// </summary>
        public static string RecommendedStudentBlockRatingLabel {
            get {
                return ResourceManager.GetString("RecommendedStudentBlockRatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procura por ajuda em.
        /// </summary>
        public static string RecommendedStudentBlockSeeksHelpLabel {
            get {
                return ResourceManager.GetString("RecommendedStudentBlockSeeksHelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similaridade com seu perfil.
        /// </summary>
        public static string RecommendedStudentBlockSimilarityLabel {
            get {
                return ResourceManager.GetString("RecommendedStudentBlockSimilarityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estes instrutores foram recomendados para você de acordo com suas &lt;a href=&quot;/Preference&quot;&gt;preferências&lt;/a&gt;.
        /// </summary>
        public static string RecommendedStudentsSectionSubtitle {
            get {
                return ResourceManager.GetString("RecommendedStudentsSectionSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrutores recomendados para você.
        /// </summary>
        public static string RecommendedStudentsSectionTitle {
            get {
                return ResourceManager.GetString("RecommendedStudentsSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua requisição no {0}.
        /// </summary>
        public static string RequestReponseEmailSubject {
            get {
                return ResourceManager.GetString("RequestReponseEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Campos obrigatórios.
        /// </summary>
        public static string RequiredFieldsText {
            get {
                return ResourceManager.GetString("RequiredFieldsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 resposta.
        /// </summary>
        public static string SingleAnswerText {
            get {
                return ResourceManager.GetString("SingleAnswerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribuições feitas por este estudante.
        /// </summary>
        public static string StudentContributionsSectionTitle {
            get {
                return ResourceManager.GetString("StudentContributionsSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Olá &lt;b&gt;{0}&lt;/b&gt;,&lt;/p&gt;&lt;p&gt;{1}&lt;/p&gt;.
        /// </summary>
        public static string StudentDefaultEmailContent {
            get {
                return ResourceManager.GetString("StudentDefaultEmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assuntos que este estudante pode te ajudar.
        /// </summary>
        public static string StudentTagsSectionTitle {
            get {
                return ResourceManager.GetString("StudentTagsSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtre as perguntas por título e/ou tags.
        /// </summary>
        public static string TimelineFilterModalTitle {
            get {
                return ResourceManager.GetString("TimelineFilterModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrando perguntas com a tag &quot;{0}&quot;.
        /// </summary>
        public static string TimelineFilterTextWithTag {
            get {
                return ResourceManager.GetString("TimelineFilterTextWithTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrando perguntas com as tags {0}.
        /// </summary>
        public static string TimelineFilterTextWithTags {
            get {
                return ResourceManager.GetString("TimelineFilterTextWithTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrando perguntas que contém &quot;{0}&quot; no título.
        /// </summary>
        public static string TimelineFilterTextWithTitle {
            get {
                return ResourceManager.GetString("TimelineFilterTextWithTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrando perguntas contendo &quot;{0}&quot; no título {1} com a tag &quot;{2}&quot;.
        /// </summary>
        public static string TimelineFilterTextWithTitleTag {
            get {
                return ResourceManager.GetString("TimelineFilterTextWithTitleTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrando perguntas contendo &quot;{0}&quot; no título {1} contendo as tags {2}.
        /// </summary>
        public static string TimelineFilterTextWithTitleTags {
            get {
                return ResourceManager.GetString("TimelineFilterTextWithTitleTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início.
        /// </summary>
        public static string TimelineViewTitle {
            get {
                return ResourceManager.GetString("TimelineViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escreva mais detalhes sobre sua pergunta.
        /// </summary>
        public static string TypeQuestionDescriptionText {
            get {
                return ResourceManager.GetString("TypeQuestionDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite sua pergunta.
        /// </summary>
        public static string TypeQuestionTitleText {
            get {
                return ResourceManager.GetString("TypeQuestionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offline.
        /// </summary>
        public static string UserOfflineStatusText {
            get {
                return ResourceManager.GetString("UserOfflineStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to online.
        /// </summary>
        public static string UserOnlineStatusText {
            get {
                return ResourceManager.GetString("UserOnlineStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para que a videoconferência que você participou seja disponibilizada para os outros estudantes, uma pergunta deve ser criada.
        ///Crie uma pergunta com assunto tratado na videoconferência e nós vamos associá-la à pergunta para você!.
        /// </summary>
        public static string VideoAnswerQuestionCreationModalMessage {
            get {
                return ResourceManager.GetString("VideoAnswerQuestionCreationModalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail ou senha incorretos.
        /// </summary>
        public static string WrongUserOrPasswordErrorMessage {
            get {
                return ResourceManager.GetString("WrongUserOrPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
